# Generated by Django 5.1.1 on 2024-10-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CB22_calibration',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('WALL', models.IntegerField()),
                ('CB', models.IntegerField()),
                ('ROB', models.IntegerField()),
                ('FEB', models.IntegerField()),
                ('Channel', models.IntegerField()),
                ('Chi2NDF', models.CharField(max_length=45)),
                ('N0', models.CharField(max_length=45)),
                ('Error_N0', models.CharField(max_length=45)),
                ('Q0', models.CharField(max_length=45)),
                ('Error_Q0', models.CharField(max_length=45)),
                ('Q1', models.CharField(max_length=45)),
                ('Error_Q1', models.CharField(max_length=45)),
                ('Sigma0', models.CharField(max_length=45)),
                ('Error_sigma0', models.CharField(max_length=45)),
                ('Sigma1', models.CharField(max_length=45)),
                ('Error_sigma1', models.CharField(max_length=45)),
                ('w', models.CharField(max_length=45)),
                ('Error_w', models.CharField(max_length=45)),
                ('alpha', models.CharField(max_length=45)),
                ('Error_alpha', models.CharField(max_length=45)),
                ('mu', models.CharField(max_length=45)),
                ('Error_mu', models.CharField(max_length=45)),
                ('Chi2NDF_pedestal', models.CharField(max_length=45)),
                ('Chi2NDF_peak', models.CharField(max_length=45)),
                ('Max_Q1_channel', models.CharField(max_length=45)),
                ('gain', models.CharField(max_length=45)),
                ('mode', models.IntegerField()),
                ('HV', models.IntegerField()),
            ],
            options={
                'db_table': 'cb22_calibration',
                'ordering': ['-id'],
            },
        ),
    ]
