# Generated by Django 5.1.1 on 2024-10-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb22', '0002_cb_list_mode_list_rob_list_wall_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cb22_calibration',
            name='FEB',
            field=models.IntegerField(default=61),
        ),
    ]
